#ifndef CommonCS
#define CommonCS
#define ArrayStruct(StructName ,T, Num) struct StructName { T buffer[Num]; int index; int MaxCount; \
        void Add(T input)\
        { buffer[index] = input; index++;}\
        \
        T Last()\
        { return buffer[index-1];\
        } \
        void Init(){ MaxCount = Num; index = 0;}\
        void SwapAndRemove(int targetIndex){T temp = buffer[index-1]; buffer[targetIndex] = temp; index--; }};\
        
        
#endif